// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwtwcsfcrfpkrktbkgbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3dHdjc2ZjcmZwa3JrdGJrZ2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzIwNzksImV4cCI6MjA2MzA0ODA3OX0.fQCAYTPyXLIqDnWox5uXUJe1-8vxVoVIQFAewb0xwHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);